// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63nz353N2BshwKg7i8sQ7VxsPngups9c',
    appId: '1:452675873664:web:69d62ed33edece4bccef65',
    messagingSenderId: '452675873664',
    projectId: 'task-manager-281b3',
    authDomain: 'task-manager-281b3.firebaseapp.com',
    storageBucket: 'task-manager-281b3.firebasestorage.app',
    measurementId: 'G-YP70XWV03K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApoFTgzMQggeAdXq7FDJIHHCcEpstS4B0',
    appId: '1:452675873664:android:1d589589891b260dccef65',
    messagingSenderId: '452675873664',
    projectId: 'task-manager-281b3',
    storageBucket: 'task-manager-281b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxadnYrSoTweSjpgyiOM0GgeYptEWX_as',
    appId: '1:452675873664:ios:a48d4a33a1b89e29ccef65',
    messagingSenderId: '452675873664',
    projectId: 'task-manager-281b3',
    storageBucket: 'task-manager-281b3.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxadnYrSoTweSjpgyiOM0GgeYptEWX_as',
    appId: '1:452675873664:ios:a48d4a33a1b89e29ccef65',
    messagingSenderId: '452675873664',
    projectId: 'task-manager-281b3',
    storageBucket: 'task-manager-281b3.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC63nz353N2BshwKg7i8sQ7VxsPngups9c',
    appId: '1:452675873664:web:9dbae003a8128cd1ccef65',
    messagingSenderId: '452675873664',
    projectId: 'task-manager-281b3',
    authDomain: 'task-manager-281b3.firebaseapp.com',
    storageBucket: 'task-manager-281b3.firebasestorage.app',
    measurementId: 'G-71KR8BEDGH',
  );
}
